{% set name = "flock" %}
{% set version = "0.4.0" %}
{% set sha256 = "c98617f1f29d2fee64b59496a147b3d17b496324a76a007c4bf5ff6b5853b7f7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/discoteq/flock/releases/download/v{{ version }}/flock-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}   # [osx]

    - which flock
    - flock my.lock echo "hello, world!"

about:
  home: https://github.com/discoteq/flock
  license: ISC
  license_file: LICENSE.md
  summary: flock(1) locks files

  dev_url: https://github.com/discoteq/flock

extra:
  recipe-maintainers:
    - jakirkham
