travis:
  secure:
    BINSTAR_TOKEN: kSWGRa6P5/ft/0dge2+nPdMYxA5soZ8HYiqUTI+oe+cWNKLsF5kTGgJJSk8q8Ld7Z+Ueaz47avq375fvmKT7AoPg8SYfCR83qyfIswE5WbEfmB2G1k4PdPFD/jXdlJOo9CC/9+bijztLUnieBHjwTiJybcV4PgZsOmzBAPsiySK4JwFJhmpQIM7YUAcGISb1ytY2yo/ToFqveKhHLX5n+TpEAzBODxJMu1ISRYOAske1Nmo1BryzKMcF+rCVJt6sDe/Bjv8z81KyhpMh2giuiCFtF8/twZVrRnlUzOILO290851PFY95CI2EXMFyZsseLi7DCGYiRRygJJmPMwdAhPvwf/+tJvlLdrry1tBG3zfwz9d4dc7QZ2KIkZt7HAT695+yWPNJFM+WH3/FWrN7ih3R1EkKF/xYuR4S6tAXP71q5dMVehbnTm9bxjlekDr1+xK4u+Lsy9XnIX1YxdDI4xyQHfWnsOUfWHR7BsnZh5GffRSedmM6I9TzUp23LsPrn3HSiMQPgDz+sltl4pSYQA0iBucxSHX9yPVMfN0hEVGUwH+AHc8ie7iboc5HjZqPwWrCApDT+mCLvwavAl3ZcJmHfEVj3EnRt/r9Vm8FZ58snAxCsOmsd5cDEkG4gmvKnhMI4E69fUdOj8McASfQaKY1TrOT7mNdVapGu+lkLf4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
