conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
build_platform:
  linux-aarch64: linux-64
  linux-ppc64le: linux-64
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: default
  linux_ppc64le: default
test: native_and_emulated
