appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ciHpTBNb+i6DnZINb9QhA6H3x2K1LGYOfrR4dwwSeuq9UInzxNESmHxu5fTHse6sWEIYY5oJZFUsloXFkjFeQZHzMSNb5KlSYsfZBtDuEkgnK9IyrZdLwqqgQivs0wmUi/FsTPKd0hp6Elt8+TXE9cYst1rCvurrYnQ4KgFYz04T+2bsI9UREnyR3df2lyL+yJDR0cI6Jns4CCjS7QLlex/mdwHE4sh3USejmMofjLdF3i2wpr95g9H4xVuf4fgWrzYET2qokaYCcJnrwDcEobh+QoHHhXrY31UYOEwUJyNUNmyya0vVI1x4S3mJQJgNA4LJnqiBptPpABa23SBaX4NJ6H2KOz1iJlsL9GW/0wskUEtfhJofE1HF9MfIJ/c6CGB6zEMF0p43fkiXBKvsdIHM/ZgEpLTTyJ+jrW+kAeyUo65QyGP6qy0Tep2A5lHWWW1LoWdQVOMRDiLEtG7pPnGBGqy+v3u+UwdXLLZApdEdcwjjXXhKedPpzkRdek2J0kvBH74DNOuj0OzTTKYAmCKJrw6Ivqu3wtDZJryunG3iV2+YB8A2PcWwga3vyu3Y3VJaDBOiq1eKCFLb9J55OUkc0+X2DxKNIf64Y6zxhnhq7x0tJgQ0m1IH/ZFU1dxPyqd2vSREUFTVHq6E3Tc2gTAHate3hxBSSmF7X3aorpM=}
